#!/bin/sh

# fzf
source /usr/share/fzf/completion.zsh
source /usr/share/fzf/key-bindings.zsh

# miniconda
source /opt/miniconda/etc/profile.d/conda.sh

# atuin
export ATUIN_NOBIND="true"
eval "$(atuin init zsh)"

bindkey '^[r' _atuin_search_widget

# zoxide
eval "$(zoxide init zsh)"

# direnv
eval "$(direnv hook zsh)"

# asdf
export ASDF_DATA_DIR="${XDG_DATA_HOME}/asdf"
export ASDF_CONFIG_FILE="${XDG_CONFIG_HOME}/asdf/asdfrc"
. /opt/asdf-vm/asdf.sh

# fnm
export PATH="${XDG_DATA_HOME}/npm/bin:$PATH"
export NPM_CONFIG_USERCONFIG="${XDG_CONFIG_HOME}/npm/npmrc"
eval "$(fnm env --use-on-cd)"

# starship
eval "$(starship init zsh)"
