#!/bin/sh

# fzf
znap eval fzf 'fzf --zsh'

# atuin
export ATUIN_NOBIND="true"
znap eval atuin 'atuin init zsh'

bindkey '^[r' _atuin_search_widget

# zoxide
znap eval zoxide 'zoxide init zsh'

# direnv
znap eval direnv 'direnv hook zsh'

# starship
znap eval starship 'starship init zsh --print-full-init'
znap prompt
