#!/bin/sh

[ -x "$(command -v nvim)" ] && alias v="nvim" vim="nvim"

# sudo not required for some system commands
for command in updatedb shutdown poweroff reboot netstat iptables ipset lsof; do
    alias $command="sudo $command"
done; unset command

# quiet mode
alias \
    bc="bc -ql" \
    pc="proxychains -q" \
    trans="trans -no-warn" \
    newsboat="newsboat -q" \
    ffmpeg="ffmpeg -hide_banner" \
    ffprobe="ffprobe -hide_banner" \
    ncmpcpp="ncmpcpp -q"

# verbose mode
alias \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -vI" \
    mkd="mkdir -pv"

# color output
alias \
    tree="tree -CAa -I '.git|node_modules' --dirsfirst" \
    ip="ip -color=auto" \
    diff="diff --color=auto" \
    ls="ls -hNv --color=auto --group-directories-first" \
    grep="grep --color=auto --exclude-dir={.git,node_modules,dist} --exclude='*.zwc'"

# abbreviate long commands
alias \
    r="ranger" \
    open="exo-open" \
    cs="cowsay" \
    fl="figlet" \
    py="python" \
    ipy="ipython" \
    ll="ls -l" \
    lsd="ls -d */" \
    tb="nc termbin.com 9999" \
    ssh="TERM=xterm-256color ssh" \
    mycli="mycli --myclirc ~/.config/mycli/myclirc" \
    iredis="iredis --iredisrc ~/.config/iredis/iredisrc" \
    yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME/yarn/config"' \
    exa="exa --icons --group-directories-first" \
    proxy="export http_proxy=http://127.0.0.1:9981 https_proxy=http://127.0.0.1:9981" \
    unproxy="unset http_proxy https_proxy" \
    dfm='/usr/bin/git --git-dir="$HOME/.local/share/dotfiles.git" --work-tree="$HOME"'

# rsync related
alias \
    rsync-cp="rsync -avzhP" \
    rsync-mv="rsync -avzhP --remove-source-files" \
    rsync-update="rsync -avzhP -u" \
    rsync-sync="rsync -avzhP -u --delete"

# swallow stuff
alias \
    mpv="swallow mpv" \
    zeal="swallow zeal" \
    zathura="swallow zathura"

# alias mpv="mpv --wid=$(xdotool getactivewindow)"

# just for convinence
alias \
    jq="jq --indent 4" \
    freeze="freeze -c user"

# terminal specific
if [ "$TERM" = "xterm-kitty" ]; then
    alias \
        ssh="kitty +kitten ssh" \
        icat="kitty +kitten icat" \
        rg="kitty +kitten hyperlinked_grep"
fi
