# 断点续传
continue

file-allocation=none

min-split-size=5M

max-connection-per-server=4

http-proxy=http://127.0.0.1:9981
https-proxy=http://127.0.0.1:9981

quiet=true

# 下载文件保存路径
dir=${HOME}/Downloads

# 日志级别
log-level=error

on-download-complete=exit
