[general]
import = ["/home/sy/.config/alacritty/themes/colorscheme.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
vi_mode_style = "Block"

[cursor.style]
blinking = "Off"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 18

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[terminal.shell]
program = "/usr/bin/zsh"

[window]
dynamic_title = false
opacity = 0.8
title = "Scratchpad"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 0
y = 0
